controllers:
  resource: ../src/Controller/
  type: attribute

app_cgv:
  path: /cgv
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'static/cgv.html.twig'
